# Generated by Django 3.2.3 on 2021-06-16 21:20

from django.db import migrations, models
import django.db.models.deletion
import screens.models.source


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0015_source_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='interspersed_source',
            field=models.ForeignKey(blank=True, default=None, help_text='Optional. Plays randomly between other content', null=True, on_delete=django.db.models.deletion.SET_NULL, to='screens.source'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='interspersed_source',
            field=models.ForeignKey(blank=True, default=None, help_text='Optional. Plays randomly between other content', null=True, on_delete=django.db.models.deletion.SET_NULL, to='screens.source'),
        ),
        migrations.AlterField(
            model_name='source',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=screens.models.source.get_file_path),
        ),
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(choices=[('IMG', 'Image'), ('VID', 'Video'), ('FRM', 'Website'), ('YTV', 'YouTube Video')], max_length=3),
        ),
    ]
